# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "demandbase"
  s.version = "0.1.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Lee Reilly"]
  s.date = "2013-03-15"
  s.description = "Ruby wrapper for the Demandbase API"
  s.email = "lee@leereilly.net"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    "CHANGELOG.md",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "demandbase.gemspec",
    "lib/demandbase.rb",
    "lib/demandbase/error.rb",
    "lib/demandbase/record.rb",
    "test/helper.rb",
    "test/test_demandbase.rb",
    "test/test_record.rb"
  ]
  s.homepage = "http://github.com/leereilly/demandbase"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.23"
  s.summary = "Ruby wrapper for the Demandbase API"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<json>, ["~> 1.7.7"])
      s.add_runtime_dependency(%q<public_suffix>, ["~> 1.2.0"])
      s.add_runtime_dependency(%q<rest-client>, ["~> 1.6.7"])
      s.add_development_dependency(%q<bundler>, ["~> 1.2.1"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.3"])
      s.add_development_dependency(%q<mocha>, ["~> 0.13.3"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<shoulda>, [">= 3.3.2"])
    else
      s.add_dependency(%q<json>, ["~> 1.7.7"])
      s.add_dependency(%q<public_suffix>, ["~> 1.2.0"])
      s.add_dependency(%q<rest-client>, ["~> 1.6.7"])
      s.add_dependency(%q<bundler>, ["~> 1.2.1"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
      s.add_dependency(%q<mocha>, ["~> 0.13.3"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<shoulda>, [">= 3.3.2"])
    end
  else
    s.add_dependency(%q<json>, ["~> 1.7.7"])
    s.add_dependency(%q<public_suffix>, ["~> 1.2.0"])
    s.add_dependency(%q<rest-client>, ["~> 1.6.7"])
    s.add_dependency(%q<bundler>, ["~> 1.2.1"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
    s.add_dependency(%q<mocha>, ["~> 0.13.3"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<shoulda>, [">= 3.3.2"])
  end
end

